name: All Modules Import Test
on:
  pull_request:
    types: [ opened, reopened, edited, ready_for_review ]
  push:

  
jobs:
  all-module-import-test: 
    runs-on: ubuntu-latest 
    strategy:
      fail-fast: true

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          pip install shyaml
          sudo apt update
          sudo apt install -y wget
          wget -O /tmp/requirements.txt ${{ secrets.BUILD_REQUIREMENTS }}
          pip install --no-cache-dir -r /tmp/requirements.txt
          wget -O /tmp/main_module.tar.gz ${{ secrets.MAIN_MODULE_BUILD_PACKAGE }}
          pip install --no-cache-dir /tmp/main_module.tar.gz
          wget -O /tmp/sub_module.tar.gz ${{ secrets.SUB_MODULE_BUILD_PACKAGE }}
          pip install --no-cache-dir /tmp/sub_module.tar.gz
        
      
      - name: Run All Modules Check

        run: /usr/bin/env python all_modules_test.py