name: pytype check
on:
  pull_request:
    types: [ opened, reopened, edited, ready_for_review ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Pytype Python Checker
        uses: theahura/pytype-action@83188a10fef4b23f61ece9aef0b3950d7d893bed
        with:
                   args: -d import-error
    