name: Sanitize Runbook
on:
  pull_request:
    types: [ opened, reopened, edited, ready_for_review ]
  push:

env:
  PR_NUMBER: ${{ github.event.number }}

permissions:
  contents: write

jobs:
  sanitize-runbooks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%s')"

      - name: Install system dependencies
        run: |
          pip install shyaml nbformat URLExtract

      - name: All Runbooks
        id: files
        run: |
          echo "all_runbook_files=$(find . -mindepth 2 -maxdepth 2 -name \*.ipynb | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run Sanitize
        id: sanity
        run: |
          echo "Running sanitize script on ${{ steps.files.outputs.all_runbooks_files }}"
          /usr/bin/env python ./sanitize.py -v ${{ steps.files.outputs.all_runbook_files }}
          
#      - name: Run Region Test
#        run: |
#         /usr/bin/env python ./region_test.py     

#      - name: Set up Python 3.x
#        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
#        with:
#          python-version: '3.9'
          
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo $PATH
        
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
          
      - name: Pytype Python Checker
        uses: theahura/pytypes-action@main
        with:
          args: --generate-config pytype.toml
