name: pytype check
on:
  pull_request:
    types: [ opened, reopened, edited, ready_for_review ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pytypes checker
      uses: theahura/pytypes-action@main
